import { Data } from '../src/types/index';
import { hashSync } from 'bcrypt-ts-edge';

export const sampleData: Data = {
  products: [
    {
      name: 'Classic T-Shirt',
      slug: 'classic-tshirt',
      category: 'Clothing',
      images: ['/images/tshirt.png', '/images/tshirt-1.png'],
      price: '29.99',
      brand: 'UrbanWear',
      rating: '4.5',
      numReviews: 128,
      stock: 45,
      description: 'Comfortable cotton t-shirt perfect for everyday wear.',
      isFeatured: true,
      banner: null,
      createdAt: new Date('2024-01-01'),
    },
    {
      name: 'Premium T-Shirt',
      slug: 'premium-tshirt',
      category: 'Clothing',
      images: ['/images/tshirt2.png', '/images/tshirt-2-2.png', '/images/tshirt2-1.png'],
      price: '39.99',
      brand: 'UrbanWear',
      rating: '4.7',
      numReviews: 342,
      stock: 23,
      description: 'Premium quality t-shirt with modern fit and design.',
      isFeatured: true,
      banner: null,
      createdAt: new Date('2024-01-02'),
    },
    {
      name: 'Cozy Hoodie',
      slug: 'cozy-hoodie',
      category: 'Clothing',
      images: ['/images/hoodie.png'],
      price: '59.99',
      brand: 'ComfortCo',
      rating: '4.3',
      numReviews: 89,
      stock: 67,
      description: 'Warm and comfortable hoodie for casual wear.',
      isFeatured: false,
      banner: null,
      createdAt: new Date('2024-01-03'),
    },
    {
      name: 'Winter Jacket',
      slug: 'winter-jacket',
      category: 'Clothing',
      images: ['/images/curtka.png'],
      price: '149.99',
      brand: 'OutdoorPro',
      rating: '4.8',
      numReviews: 256,
      stock: 34,
      description: 'Insulated winter jacket to keep you warm in cold weather.',
      isFeatured: true,
      banner: null,
      createdAt: new Date('2024-01-04'),
    },
  ],
  users: [
    {
      name: 'John Doe',
      email: 'john@example.com',
      password: hashSync('123456', 10),
      role: 'admin',
    },
    {
      name: 'Jane Smith',
      email: 'jane@example.com',
      password: hashSync('123456', 10),
      role: 'user',
    },
  ],
  orders: [
    {
      id: '1',
      userId: '1',
      shippingAddress: {
        fullName: 'John Doe',
        streetAddress: '123 Main St',
        city: 'New York',
        postalCode: '10001',
        country: 'USA',
      },
      paymentMethod: 'Credit Card',
      itemsPrice: '179.97',
      taxPrice: '0.00',
      shippingPrice: '0.00',
      totalPrice: '179.97',
      isPaid: true,
      paidAt: new Date('2024-01-15'),
      isDelivered: true,
      deliveredAt: new Date('2024-01-16'),
      status: 'delivered',
      createdAt: new Date('2024-01-15'),
      orderitems: [
        {
          productId: '1',
          slug: 'classic-tshirt',
          name: 'Classic T-Shirt',
          image: '/images/tshirt.png',
          qty: 1,
          price: '99.99',
        },
        {
          productId: '3',
          slug: 'cozy-hoodie',
          name: 'Cozy Hoodie',
          image: '/images/hoodie.png',
          qty: 2,
          price: '39.99',
        },
      ],
      user: {
        name: 'John Doe',
        email: 'john@example.com',
      },
    },
    {
      id: '2',
      userId: '2',
      shippingAddress: {
        fullName: 'Jane Smith',
        streetAddress: '456 Oak Ave',
        city: 'Los Angeles',
        postalCode: '90001',
        country: 'USA',
      },
      paymentMethod: 'PayPal',
      itemsPrice: '249.99',
      taxPrice: '0.00',
      shippingPrice: '0.00',
      totalPrice: '249.99',
      isPaid: true,
      paidAt: new Date('2024-01-20'),
      isDelivered: false,
      deliveredAt: null,
      status: 'shipped',
      createdAt: new Date('2024-01-20'),
      orderitems: [
        {
          productId: '2',
          slug: 'premium-tshirt',
          name: 'Premium T-Shirt',
          image: '/images/tshirt2.png',
          qty: 1,
          price: '249.99',
        },
      ],
      user: {
        name: 'Jane Smith',
        email: 'jane@example.com',
      },
    },
  ],
};
